# Generated by Django 3.2 on 2021-05-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210510_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meetingTime',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingDate',
            field=models.DateTimeField(),
        ),
    ]
