# Generated by Django 3.2 on 2021-05-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20210510_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventTime',
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(),
        ),
    ]
